### ISSUE TITLE
Duplicate Spinner export in index.d.ts

### ISSUE THREAD

**Issue by nartc** [tuantvk/monalisa-ui#10]
![image](https://user-images.githubusercontent.com/25516557/70378933-5e337300-18ec-11ea-8e36-2a4e437c0e69.png)

Duplicate `Spinner` export in typings file.

**Comment by tuantvk** [comment]
@nartc  i fixed in [https://github.com/tuantvk/monalisa-ui/commit/b65d823288b762a60e3e0bef3324db3b1f366203](https://github.com/tuantvk/monalisa-ui/commit/b65d823288b762a60e3e0bef3324db3b1f366203). Thanks for review :tada:
