### ISSUE TITLE
MonalisaUI Dependencies

### ISSUE THREAD

**Issue by nartc** [tuantvk/monalisa-ui#12]
![image](https://user-images.githubusercontent.com/25516557/70442868-bb4e3680-1a5c-11ea-95f2-333fa75b38e4.png)
Why are `react-navigation`(and related navigation libraries) a part of a UI Library's dependencies?

**Comment by tuantvk** [comment]
ya! react-navigation and related navigation libraries is independent to each other. It's for development write example.
@nartc thanks. i update in [https://github.com/tuantvk/monalisa-ui/commit/d44c6b77e7698cd73da8a61c94b7e532c5f19c38](https://github.com/tuantvk/monalisa-ui/commit/d44c6b77e7698cd73da8a61c94b7e532c5f19c38)
