### ISSUE TITLE
Expose component Props (TypeScript) to allow Type Composition

### ISSUE THREAD

**Issue by nartc** [tuantvk/monalisa-ui#9]
Hi,

It seems that the library does support TypeScript type definition. However, the individual props of each component isn't exposed. This makes it harder to extends the Props if a library consumer wants to abstract this library's components in their project. 

For example:  if I want to have a `Switch` component with a `Text` as label and it's very specific to my application, without the type def exposed, it's awkward to write an abstract component for that.

```typescript
import { SwitchProps } from 'monalisa-ui'

interface Props extends SwitchProps { // this would allow better customizability 
}
```

**Comment by tuantvk** [comment]
@nartc Thanks for issues. I have update in version [v0.3.0](https://github.com/tuantvk/monalisa-ui/releases/tag/v0.3.0). Please advise :ok_hand:

**Comment by nartc** [comment]
I'll take a look asap
